apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBQCcaZ6iZsNQD1klLT34Ul65ylCQ+sIhv0EoAMzrlSYWs1GpTwJLh8B8YCOxtdj2uFAtW0/42ppHh1URL4dcUDGBkB+XZpqdMNeLIE8XPyNYDszUdZWn/aL9vRzHOs8ZTppw7lPp9icirkVdkrxHXzzyLZSXf+PFuprD5w7K+Wo0X/Haf9rGI4M+E+qIy1uXcjqCSvellPsOKyXfYA6QNIrp8UacFjYFxW1CU1i/MzDXb/JWIazJU2fi+EuZWEVp/N7Bdq/ZaYNUPlNzmYyBXCTAJ1W2QKSFOK+5dOuWq9Tdf2hVz7scsHrKKCSuuYjbY+548v4DWNbtCW4zQff0firWxOD06nVLoa8VUb3alCmDUEJECHw1pBn/YTOTntKtKQobRD+C2BsDVFQtXUS+3+0aYXFxEfBnFmPVJAiM3WlPfkaiMS+dg3YeCfNGEXz2OKH6RPiMs5r9h28odHTyg8UoHohQawWfU6g3YU195SKcA1dpgRQjeNGEGQYh4hKhqp0Ec4cKK3IEWBAmOzQH9vkTBcN10zSbBdmke0fH8sLVv2XddQh1AX6so15PmCM6vFloTu3K0avMmxrWRimfuDpb4ZXgW2xI05RoCC9btikwRuITBfX7+SDSaeBKohWG8QIQFXSXDT1rwDeXi30q5H4iL5CTFkUTHemeYJFUoiOyZj+07kndhkVBQEhfCplbg4RxXkRgwpng==
    DB_USER: AgBOkTv1Y4icMYU93HRuRaO6zhfeccaVZSuJT6UgTd7R0T3rEDQIsQ2/xRxesG8GjzNFqTlcDWwQh6vQGl8GgTZwSEICAS+bhLpADsgiHpsEmbrevJW5wiLPxZzwkEJUsgGC3Ink2Bw9Ph9uEm+oT+q+MrcppEEU73gBzHVMh5PRHLwnZrgbDSf1m9g73KyFQdS5uSOujVqilHg0qsuB6wQ75Q5NBxfaJ2M1z2VQ0uuV4gRBg5F6vi24WRt9Uyk+3oiN2Zn0EKjAaHZFIQvI2QE+e0EQLknp0NwoaT8noDOxAVv5a2lfsM2SHp0UF86Q+KPLPZHErSpX8mvuujTCMKfOnWV2Xe6wyJ9QsdHz3Ops8Qz7uvI5nemEQVtKHCxrD0jpUCVN1oZwhrYv24/WhoZpCuWVNHCywAr1nXi600k6u7L+1TO5H/Lb080K3641CkQUV4/bnImi9Yu8a9APzcPGdzkgYNbCgquHIRVpMhFMrUgf92VFQ1QEP/mWjBY57Xc9R/wS8buT4zUfmR7R39I+GWZtrVEf3znOS84hvTgpwHxWtiTdpUf++vJhPPGNh0rFJpiJo49OCkyUum5UPVziTWapTjrfNugwiupw6GQc5diRTCT9krFkqwU83nD12GqQ5NBdwOKIoVfjjYXo8RsIAoqV6cjwrxasElFhMwKXfFfu1oe/UaKJszMnClWQ54rTv0/9Te8Cmg==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

