apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBfDt5+2jC2HMO7UxPJVJFVJj4+ntwzlvaevv870Z7D70fvo0jALTrIV1bAvRscW4MYkLgdiSU41Ayiwx6HpTFPebO2AzLwUqq8MKGtxcoWVN89DTABpO3wPsRxV3cQ5dWJmkua5QU1IeLJplleTj+faSpKwtY/UK0sDiIS7L682Lj26DFAG80KSW6Q5bBIa/0+mx+2HVMa7/YJ77LmR3ZQU+jjwoREjXyGFHllfwVlZI60n4c5vcyPTTbUfDktzn1XrMslEUvPh3RsG9mtUdpvJy7uhswrFXa7qZ9T2LOblsuRTE0D7QmhjVfoMor/cig6/ZCq/O++eY2MexgynPaYcJGJTtc/mMXB/ogtGX+qS73paex/Q2HZ0k3xjDMXcHVZQ9o2oJXnorXlNrJW0Q9i1pkofoo3RGzdL1XdSVZdg+e8jl9UlmELOSNZznJfn0MyufUXz+6ObBElf5OMFKFSp2V1CSkg+fqQuJToy7bh3FF0rf6AD2CEqnCrCash0r69rwn6bnOr5h6Nyy8XT/TsCvUYjhXiqf96+HATzTybZzJ+t0B7wkow7ekFxUlOySL4w3i2i3IOMq77legRurlTA49Os2DROycLr9YH/6QT0cl+mM4ApS5yXTl5FQQpV8mS9vM0WWKTRREKDPF8sqwTJUHHs3QdMhZ/G6S1/mJMajbqir1DWK8idondHpmGV943VIVR/FqETQ==
    DB_USER: AgBt7Y7mfOsKUAQhOg9yiaJy3vTrMrkc/0OMNQg4xYEJ+LeXXetUjimgKD1nek7O4idQf5nd+jbyr6T9AujlMsa/lZDovxZWEtUNNl6Bn4dUgtgAT4wH0pPYdv4Z3REQ8jSHU608V7bbEZAPNYhSKLQc2ou2TSyHwSsJG+M3urF/f6sAwaeXFvf+/0yQPlag4WTRwb/aEuixtIRxhV38ncAEYWc5R9j/cihdpyy1Bi72JOPQQz1ccXFkIettxcv7dl8wRKoDZjUlEIFGm7tID/TICyxTC2x5aodKUUK98jxsYRmuLqpdkJ3+devSDnVjR1kyV3F5cVkDm1SJCaGoihpBasjbDxuKVw3nIEsVhkVOfTQwA+HDVichx1Hw9a/gsVAXXjejN5cm7FRKlSuoFUlmNVxABq9zvn7cYkgj0hytHK9oFjJfz2CaMf+Y7vEdQIW222/gzNSddEiQJ4dIVcFdW7YEa5jVQ7/y3ig5XPvJNK1tyQxiCpunJmTJHZy3VMP1sWaH5d5836aKj7vPBzlGyzLJb4zK8RJP4O6KAO0WwsekIWQ7ZESYYECZKDBddiUpTs+WA9tnGjSSjjc8oQWNkAhYXk6n/V82py5QbRuound/xDLTq6iePz9gx4NBC/7Qc2MycI5dkNy/jhAk7fm6+50RVTHLG939rAlTWjgVkbmxGd2iWaaomaaIPSwGdOo8MHtqbxCi8A==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

